### ISSUE TITLE
HA 0.68  error

### ISSUE THREAD

**Issue by jyz0501** [stanzhai/homebridge-mi-gateway-light#2]
dgram.js:614
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership EADDRINUSE
    at _errnoException (util.js:1024:11)
    at Socket.addMembership (dgram.js:614:11)
    at Socket.DeveloperApi.socket.on (/usr/lib/node_modules/homebridge-mi-gateway/node_modules/miio/lib/devices/gateway/developer-api.js:42:19)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at startListening (dgram.js:156:10)
    at _handle.lookup (dgram.js:273:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by jyz0501** [comment]
是这样写吗？？不是写到下面的platform里面去？
  "description": "Homebridge for Home Assistant",
  "accessories": [
    {
      "accessory": "MiGateway",
      "ip": "192.168.31.**",
      "token": "3e046f4a******",
      "name": "小米网关",
      "fmName": "网关FM",
      "lightName": "网关灯",
      "securityName": "网关警戒"
    }
  ],

**Comment by stanzhai** [comment]
不要放到platform里，放到accessories下
